[anonymous-telemetry]
enabled = false

[source]
root_patterns = [
    "/src/python",
    "/tests",
]

[python]
interpreter_constraints = ["CPython>=3.8.*"]

[repl]
#shell = "ipython"

[pex]
verbosity=8

[pytest]
version = "pytest>=6.0"
lockfile="3rdparty/python/pytest.lockfile"

[GLOBAL]
pants_version = "2.9.0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.isort",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.typecheck.mypy",
    ]
