version: "3.7"
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2021-11-09T03-21-45Z
    container_name: minio-server
    hostname: minio
    volumes:
      - ./data:/data
    command: server /data --console-address "0.0.0.0:9001" --address "0.0.0.0:9000" 
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  httpd:
    build:
      context: apache
      dockerfile: Dockerfile
    image: apache2
    container_name: webserver
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./data:/usr/local/apache2/htdocs
    ports:
      - "9002:80"

